INVALID_STATES = "States are invalid."
INVALID_ALPHABET = "Alphabet is invalid."
INVALID_INITIAL_STATE = "Initial state is invalid."
INVALID_FINAL_STATES = "Final states are invalid."
INVALID_TRANSITIONS = "Transitions are invalid."
